# ArgoCD Application — GitOps-деплой FastAPI-сервісу з Helm-чарту в цьому репо.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiops-quality
  namespace: infra-tools # де встановлено ArgoCD
spec:
  project: default
  source:
    repoURL: https://github.com/DenysRudenko2/final-project.git
    targetRevision: main
    path: helm
    helm:
      releaseName: aiops-quality
  destination:
    server: https://kubernetes.default.svc
    namespace: aiops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
